adds library/markup
VolodymyrBashtanyuk/fifty-team-js-project pull request #4
Opened 2022-08-26 10:49 UTC by OspanovaV

2022-08-26 12:21 UTC, VolodymyrBashtanyuk commented on src/sass/_library.scss
> +    list-style: none;
переглянь налаштування в reset.scss і видали які однакові

2022-08-26 12:22 UTC, VolodymyrBashtanyuk commented on src/sass/_library.scss
> +    @media screen and(min-width:480px) {
використовуй mixin

2022-08-26 12:25 UTC, VolodymyrBashtanyuk commented on src/sass/_library.scss
> +    transition: box-shadow 250ms cubic-bezier(0.4, 0, 0.2, 1);
використовуй перемінну для цього =(250ms cubic-bezier(0.4, 0, 0.2, 1)

2022-08-26 12:27 UTC, VolodymyrBashtanyuk commented on src/sass/_container.scss
> +.container {
видали у нас є контайнер

2022-08-26 12:28 UTC, VolodymyrBashtanyuk commented on src/sass/_library.scss
> +.list,
перемісти _library.scss в папку  components і перевір шляхи пидключення

2022-08-26 12:32 UTC, VolodymyrBashtanyuk requested changes
Виправи бьдь ласка

2022-08-26 22:21 UTC, Rechkalov1 reviewed
На мой взгляд все норм, перепроверьте

2022-08-27 10:42 UTC, VolodymyrBashtanyuk approved these changes

2022-08-27 10:47 UTC, VolodymyrBashtanyuk approved these changes

2022-08-28 07:24 UTC, VolodymyrBashtanyuk approved these changes

2022-08-28 07:25 UTC, merged